Config = {}

Config.DefaultVolume = 0.7         -- 0.0 to 1.0
Config.MaxAudioDistance = 20.0     -- meters - beyond this, silent
Config.MuffleStartDistance = 5.0   -- meters - lowpass filter begins
Config.DisableNativeRadio = true   -- Disable GTA's built-in radio

-- Optional CDN base URL. When non-empty, every non-absolute `file` path in
-- the stations below is resolved against this prefix BEFORE being sent to
-- the NUI. Lets you keep the resource tiny (delete songs/ on disk) while
-- streaming audio directly from R2 / Cloudflare / Bunny / wherever.
--   ''  = serve locally from songs/ (bundled in this resource)
-- Individual entries can still hardcode a full https:// URL to override on
-- a per-track basis.
Config.CDNBaseUrl = 'https://r2.fivemanage.com/Cty8HKL0KM8fh5bWUPUU3/Radio'

-- Vehicles where the radio is disabled.
-- Class 18 = Emergency (police, ambulance, firetruck).
Config.DisableInEmergencyClass = true
-- Additional specific models by name. Example: {'police', 'police2', 'sheriff', 'riot'}
Config.DisabledVehicleModels = {}

Config.Stations = {
    {
        id = 'OB_RADIO_2',
        label = 'Sleep Token.FM',
        logo = 'sleeptoken.png',
        songs = {
            { file = "sleeptoken/bring_me_the_horizon_limousine_feat_aurora.mp3", title = "liMOusIne (feat. AURORA)", artist = "Bring Me The Horizon", duration = 200 },
            { file = "sleeptoken/if_not_for_me_feel_me_now.mp3", title = "Feel Me Now", artist = "If Not For Me", duration = 200 },
            { file = "sleeptoken/invent_animate_without_a_whisper.mp3", title = "Without a Whisper", artist = "Invent Animate", duration = 200 },
            { file = "sleeptoken/kami_kehoe_die_4_u.mp3", title = "DIE 4 U", artist = "Kami Kehoe", duration = 200 },
            { file = "sleeptoken/president_conclave.mp3", title = "Conclave", artist = "PRESIDENT", duration = 200 },
            { file = "sleeptoken/president_fearless.mp3", title = "Fearless", artist = "PRESIDENT", duration = 200 },
            { file = "sleeptoken/president_in_the_name_of_the_father.mp3", title = "In the Name of the Father", artist = "PRESIDENT", duration = 200 },
            { file = "sleeptoken/sleep_theory_gravity.mp3", title = "Gravity", artist = "Sleep Theory", duration = 200 },
            { file = "sleeptoken/sleep_theory_iii.mp3", title = "III", artist = "Sleep Theory", duration = 200 },
            { file = "sleeptoken/sleep_theory_numb.mp3", title = "Numb", artist = "Sleep Theory", duration = 200 },
            { file = "sleeptoken/sleep_theory_words_are_worthless.mp3", title = "Words Are Worthless", artist = "Sleep Theory", duration = 200 },
            { file = "sleeptoken/sleep_token_chokehold.mp3", title = "Chokehold", artist = "Sleep Token", duration = 200 },
            { file = "sleeptoken/sleep_token_jericho.mp3", title = "Jericho", artist = "Sleep Token", duration = 200 },
            { file = "sleeptoken/sleep_token_provider.mp3", title = "Provider", artist = "Sleep Token", duration = 200 },
            { file = "sleeptoken/sleep_token_take_me_back_to_eden.mp3", title = "Take Me Back To Eden", artist = "Sleep Token", duration = 200 },
            { file = "sleeptoken/sleep_token_the_apparition.mp3", title = "The Apparition", artist = "Sleep Token", duration = 200 },
            { file = "sleeptoken/sleep_token_the_summoning.mp3", title = "The Summoning", artist = "Sleep Token", duration = 200 },
            { file = "sleeptoken/spiritbox_blessed_be.mp3", title = "Blessed Be", artist = "Spiritbox", duration = 200 },
            { file = "sleeptoken/spiritbox_circle_with_me.mp3", title = "Circle With Me", artist = "Spiritbox", duration = 200 },
            { file = "sleeptoken/spiritbox_jaded.mp3", title = "Jaded", artist = "Spiritbox", duration = 200 },
            { file = "sleeptoken/spiritbox_perfect_soul.mp3", title = "Perfect Soul", artist = "Spiritbox", duration = 200 },
            { file = "sleeptoken/the_plot_in_you_closure.mp3", title = "Closure", artist = "The Plot In You", duration = 200 },
            { file = "sleeptoken/the_plot_in_you_divide.mp3", title = "Divide", artist = "The Plot In You", duration = 200 },
            { file = "sleeptoken/the_plot_in_you_left_behind.mp3", title = "Left Behind", artist = "The Plot In You", duration = 200 },
            { file = "sleeptoken/the_plot_in_you_spare_me.mp3", title = "Spare Me", artist = "The Plot In You", duration = 200 },
            { file = "sleeptoken/the_plot_in_you_the_one_you_loved.mp3", title = "THE ONE YOU LOVED", artist = "The Plot In You", duration = 200 },
            { file = "sleeptoken/wind_walkers_almost_ecstasy.mp3", title = "Almost Ecstasy", artist = "Wind Walkers", duration = 200 },
            { file = "sleeptoken/wind_walkers_feeding_the_gods.mp3", title = "Feeding the Gods", artist = "Wind Walkers", duration = 200 },
        },
    },
    {
        id = 'OB_RADIO_3',
        label = 'DnB Radio',
        logo = 'dnb.png',
        songs = {
            { file = "dnbmix/accelio_jazz_club.mp3", title = "Jazz Club", artist = "Accelio", duration = 200 },
            { file = "dnbmix/aquarious_soul_searching.mp3", title = "Soul Searching", artist = "Aquarious", duration = 200 },
            { file = "dnbmix/big_bud_fantasy.mp3", title = "Fantasy", artist = "Big Bud", duration = 200 },
            { file = "dnbmix/blksmiith_satellite_from_days_of_old_lead_me_to_your_access_code.mp3", title = "Satellite from days of old, lead me to your access code", artist = "Blksmiith", duration = 200 },
            { file = "dnbmix/errx_breaking_down.mp3", title = "breaking down", artist = "ERRx", duration = 200 },
            { file = "dnbmix/goldie_inner_city_life.mp3", title = "Inner City Life", artist = "Goldie", duration = 200 },
            { file = "dnbmix/kmc_system_instrumental_mix.mp3", title = "System - Instrumental Mix", artist = "KMC", duration = 200 },
            { file = "dnbmix/kinda_rad_jam_cannon.mp3", title = "Jam Cannon", artist = "Kinda Rad", duration = 200 },
            { file = "dnbmix/ltj_bukem_coolin_out.mp3", title = "Coolin Out", artist = "LTJ Bukem", duration = 200 },
            { file = "dnbmix/ltj_bukem_rainfall.mp3", title = "Rainfall", artist = "LTJ Bukem", duration = 200 },
            { file = "dnbmix/ltj_bukem_rhodes_to_freedom.mp3", title = "Rhodes to Freedom", artist = "LTJ Bukem", duration = 200 },
            { file = "dnbmix/phd_the_funky_technicians_above_beyond.mp3", title = "Above & Beyond", artist = "PHD & The Funky Technicians", duration = 200 },
            { file = "dnbmix/parkland_factory_settings.mp3", title = "factory settings", artist = "Parkland", duration = 200 },
            { file = "dnbmix/photek_t_raenon_original_mix.mp3", title = "T'Raenon - Original Mix", artist = "Photek", duration = 200 },
            { file = "dnbmix/pizza_hotline_mrs_hotline.mp3", title = "Mrs Hotline", artist = "Pizza Hotline", duration = 200 },
            { file = "dnbmix/q_project_solar_system_instrumental_mix.mp3", title = "Solar System - Instrumental Mix", artist = "Q Project", duration = 200 },
            { file = "dnbmix/seba_so_long.mp3", title = "So Long", artist = "Seba", duration = 200 },
            { file = "dnbmix/sewerslvt_newlove.mp3", title = "Newlove", artist = "Sewerslvt", duration = 200 },
            { file = "dnbmix/sewerslvt_goodbye.mp3", title = "goodbye", artist = "Sewerslvt", duration = 200 },
            { file = "dnbmix/sxnctuary_nitro.mp3", title = "Nitro", artist = "Sxnctuary", duration = 200 },
            { file = "dnbmix/tayla_resolution.mp3", title = "Resolution", artist = "Tayla", duration = 200 },
            { file = "dnbmix/trashiii_metal_teeth.mp3", title = "METAL TEETH", artist = "Trashiii", duration = 200 },
            { file = "dnbmix/trashiii_umd.mp3", title = "UMD", artist = "Trashiii", duration = 200 },
            { file = "dnbmix/voyager_long_distance.mp3", title = "Long Distance", artist = "Voyager", duration = 200 },
            { file = "dnbmix/voyager_possessions.mp3", title = "Possessions", artist = "Voyager", duration = 200 },
            { file = "dnbmix/boy_2000_genesis.mp3", title = "genesis", artist = "boy 2000", duration = 200 },
            { file = "dnbmix/usedcvnt_a_tear_at_eventide.mp3", title = "a tear at eventide", artist = "usedcvnt", duration = 200 },
        },
    },
    {
        id = 'OB_RADIO_4',
        label = 'Dave.FM',
        logo = 'dave.png',
        songs = {
            { file = "davemix/dave_clash_feat_stormzy.mp3", title = "Clash (feat. Stormzy)", artist = "Dave", duration = 200 },
            { file = "davemix/dave_history_feat_james_blake.mp3", title = "History (feat. James Blake)", artist = "Dave", duration = 200 },
            { file = "davemix/dave_location_feat_burna_boy.mp3", title = "Location (feat. Burna Boy)", artist = "Dave", duration = 200 },
            { file = "davemix/dave_marvellous.mp3", title = "Marvellous", artist = "Dave", duration = 200 },
            { file = "davemix/dave_no_weapons_feat_jim_legxacy.mp3", title = "No Weapons (feat. Jim Legxacy)", artist = "Dave", duration = 200 },
            { file = "davemix/dave_professor_x.mp3", title = "Professor X", artist = "Dave", duration = 200 },
            { file = "davemix/dave_psycho.mp3", title = "Psycho", artist = "Dave", duration = 200 },
            { file = "davemix/dave_raindance_feat_tems.mp3", title = "Raindance (feat. Tems)", artist = "Dave", duration = 200 },
            { file = "davemix/dave_selfish_feat_james_blake.mp3", title = "Selfish (feat. James Blake)", artist = "Dave", duration = 200 },
            { file = "davemix/dave_starlight.mp3", title = "Starlight", artist = "Dave", duration = 200 },
            { file = "davemix/dave_thiago_silva.mp3", title = "Thiago Silva", artist = "Dave", duration = 200 },
            { file = "davemix/dave_titanium.mp3", title = "Titanium", artist = "Dave", duration = 200 },
            { file = "davemix/dave_trojan_horse.mp3", title = "Trojan Horse", artist = "Dave", duration = 200 },
            { file = "davemix/dominic_fike_white_keys.mp3", title = "White Keys", artist = "Dominic Fike", duration = 200 },
            { file = "davemix/don_toliver_no_pole.mp3", title = "No Pole", artist = "Don Toliver", duration = 200 },
            { file = "davemix/don_toliver_secondhand_feat_rema.mp3", title = "Secondhand (feat. Rema)", artist = "Don Toliver", duration = 200 },
            { file = "davemix/drake_one_dance.mp3", title = "One Dance", artist = "Drake", duration = 200 },
            { file = "davemix/fredo_money_talks_feat_dave.mp3", title = "Money Talks (feat. Dave)", artist = "Fredo", duration = 200 },
            { file = "davemix/french_montana_unforgettable.mp3", title = "Unforgettable", artist = "French Montana", duration = 200 },
            { file = "davemix/giggs_peligro.mp3", title = "Peligro", artist = "Giggs", duration = 200 },
            { file = "davemix/jae5_propeller_feat_dave_bnxn.mp3", title = "Propeller (feat. Dave & BNXN)", artist = "JAE5", duration = 200 },
            { file = "davemix/jim_legxacy_3x.mp3", title = "3x", artist = "Jim Legxacy", duration = 200 },
            { file = "davemix/justin_bieber_daisies.mp3", title = "DAISIES", artist = "Justin Bieber", duration = 200 },
            { file = "davemix/kendrick_lamar_all_the_stars_with_sza_from_black_panther_the_album.mp3", title = "All The Stars (with SZA) - From _Black Panther_ The Album_", artist = "Kendrick Lamar", duration = 200 },
            { file = "davemix/olivia_dean_man_i_need.mp3", title = "Man I Need", artist = "Olivia Dean", duration = 200 },
            { file = "davemix/oxlade_intoxycated.mp3", title = "INTOXYCATED", artist = "Oxlade", duration = 200 },
            { file = "davemix/the_weeknd_timeless_feat_playboi_carti.mp3", title = "Timeless (feat Playboi Carti)", artist = "The Weeknd", duration = 200 },
        },
    },
    {
        id = 'OB_RADIO_6',
        label = 'Billie Eilish.FM',
        logo = 'billie.png',
        songs = {
            { file = "billieeilish/ariana_grande_we_can_t_be_friends_wait_for_your_love.mp3", title = "we can't be friends (wait for your love)", artist = "Ariana Grande", duration = 200 },
            { file = "billieeilish/billie_eilish_birds_of_a_feather.mp3", title = "BIRDS OF A FEATHER", artist = "Billie Eilish", duration = 200 },
            { file = "billieeilish/billie_eilish_billie_bossa_nova.mp3", title = "Billie Bossa Nova", artist = "Billie Eilish", duration = 200 },
            { file = "billieeilish/billie_eilish_bored.mp3", title = "Bored", artist = "Billie Eilish", duration = 200 },
            { file = "billieeilish/billie_eilish_halley_s_comet.mp3", title = "Halley's Comet", artist = "Billie Eilish", duration = 200 },
            { file = "billieeilish/billie_eilish_no_time_to_die.mp3", title = "No Time To Die", artist = "Billie Eilish", duration = 200 },
            { file = "billieeilish/billie_eilish_skinny.mp3", title = "SKINNY", artist = "Billie Eilish", duration = 200 },
            { file = "billieeilish/billie_eilish_the_greatest.mp3", title = "THE GREATEST", artist = "Billie Eilish", duration = 200 },
            { file = "billieeilish/billie_eilish_tv.mp3", title = "TV", artist = "Billie Eilish", duration = 200 },
            { file = "billieeilish/billie_eilish_wildflower.mp3", title = "WILDFLOWER", artist = "Billie Eilish", duration = 200 },
            { file = "billieeilish/billie_eilish_what_was_i_made_for_from_the_motion_picture_barbie.mp3", title = "What Was I Made For_ [From The Motion Picture _Barbie_]", artist = "Billie Eilish", duration = 200 },
            { file = "billieeilish/billie_eilish_bellyache.mp3", title = "bellyache", artist = "Billie Eilish", duration = 200 },
            { file = "billieeilish/billie_eilish_i_love_you.mp3", title = "i love you", artist = "Billie Eilish", duration = 200 },
            { file = "billieeilish/billie_eilish_lovely_with_khalid.mp3", title = "lovely (with Khalid)", artist = "Billie Eilish", duration = 200 },
            { file = "billieeilish/billie_eilish_ocean_eyes.mp3", title = "ocean eyes", artist = "Billie Eilish", duration = 200 },
            { file = "billieeilish/billie_eilish_watch.mp3", title = "watch", artist = "Billie Eilish", duration = 200 },
            { file = "billieeilish/billie_eilish_when_the_party_s_over.mp3", title = "when the party's over", artist = "Billie Eilish", duration = 200 },
            { file = "billieeilish/charli_xcx_guess_featuring_billie_eilish.mp3", title = "Guess featuring billie eilish", artist = "Charli xcx", duration = 200 },
            { file = "billieeilish/cigarettes_after_sex_apocalypse.mp3", title = "Apocalypse", artist = "Cigarettes After Sex", duration = 200 },
            { file = "billieeilish/conan_gray_heather.mp3", title = "Heather", artist = "Conan Gray", duration = 200 },
            { file = "billieeilish/gracie_abrams_i_love_you_i_m_sorry.mp3", title = "I Love You, I'm Sorry", artist = "Gracie Abrams", duration = 200 },
            { file = "billieeilish/harry_styles_as_it_was.mp3", title = "As It Was", artist = "Harry Styles", duration = 200 },
            { file = "billieeilish/lady_gaga_die_with_a_smile.mp3", title = "Die With A Smile", artist = "Lady Gaga", duration = 200 },
            { file = "billieeilish/lord_huron_the_night_we_met.mp3", title = "The Night We Met", artist = "Lord Huron", duration = 200 },
            { file = "billieeilish/mitski_my_love_mine_all_mine.mp3", title = "My Love Mine All Mine", artist = "Mitski", duration = 200 },
            { file = "billieeilish/sabrina_carpenter_please_please_please.mp3", title = "Please Please Please", artist = "Sabrina Carpenter", duration = 200 },
            { file = "billieeilish/the_marias_no_one_noticed.mp3", title = "No One Noticed", artist = "The Marías", duration = 200 },
            { file = "billieeilish/the_neighbourhood_sweater_weather.mp3", title = "Sweater Weather", artist = "The Neighbourhood", duration = 200 },
            { file = "billieeilish/the_weeknd_one_of_the_girls_with_jennie_lily_rose_depp.mp3", title = "One Of The Girls (with JENNIE, Lily Rose Depp)", artist = "The Weeknd", duration = 200 },
            { file = "billieeilish/sombr_back_to_friends.mp3", title = "back to friends", artist = "sombr", duration = 200 },
        },
    },
    {
        id = 'OB_RADIO_7',
        label = 'OldSchool.FM',
        logo = 'oldschool.png',
        songs = {
            { file = "oldschoolmix/2pac_ambitionz_az_a_ridah.mp3", title = "Ambitionz Az A Ridah", artist = "2Pac", duration = 200 },
            { file = "oldschoolmix/50_cent_21_questions.mp3", title = "21 Questions", artist = "50 Cent", duration = 200 },
            { file = "oldschoolmix/alexis_y_fido_camuflaje_remix.mp3", title = "Camuflaje (Remix)", artist = "Alexis y Fido", duration = 200 },
            { file = "oldschoolmix/alexis_y_fido_mala_conducta_feat_franco_el_gorila.mp3", title = "Mala Conducta (feat. Franco El Gorila)", artist = "Alexis y Fido", duration = 200 },
            { file = "oldschoolmix/calle_13_atrevete_te_te.mp3", title = "Atrévete-Te-Te", artist = "Calle 13", duration = 200 },
            { file = "oldschoolmix/daddy_yankee_no_es_culpa_mia_bonus_track.mp3", title = "No Es Culpa Mía - Bonus Track", artist = "Daddy Yankee", duration = 200 },
            { file = "oldschoolmix/daddy_yankee_pose.mp3", title = "Pose", artist = "Daddy Yankee", duration = 200 },
            { file = "oldschoolmix/daddy_yankee_que_tengo_que_hacer.mp3", title = "¿Qué Tengo Que Hacer_", artist = "Daddy Yankee", duration = 200 },
            { file = "oldschoolmix/don_omar_hasta_abajo.mp3", title = "Hasta Abajo", artist = "Don Omar", duration = 200 },
            { file = "oldschoolmix/don_omar_hooka.mp3", title = "Hooka", artist = "Don Omar", duration = 200 },
            { file = "oldschoolmix/don_omar_my_space.mp3", title = "My Space", artist = "Don Omar", duration = 200 },
            { file = "oldschoolmix/don_omar_sexy_robotica.mp3", title = "Sexy Robotica", artist = "Don Omar", duration = 200 },
            { file = "oldschoolmix/dr_dre_forgot_about_dre.mp3", title = "Forgot About Dre", artist = "Dr. Dre", duration = 200 },
            { file = "oldschoolmix/dr_dre_nuthin_but_a_g_thang.mp3", title = "Nuthin' But A _G_ Thang", artist = "Dr. Dre", duration = 200 },
            { file = "oldschoolmix/farruko_hola_beba.mp3", title = "Hola Beba", artist = "Farruko", duration = 200 },
            { file = "oldschoolmix/j_alvarez_sexo_sudor_y_calor.mp3", title = "Sexo, Sudor y Calor", artist = "J Alvarez", duration = 200 },
            { file = "oldschoolmix/justin_quiles_esta_noche.mp3", title = "Esta Noche", artist = "Justin Quiles", duration = 200 },
            { file = "oldschoolmix/kishore_kumar_ek_ajnabee_haseena_se.mp3", title = "Ek Ajnabee Haseena Se", artist = "Kishore Kumar", duration = 200 },
            { file = "oldschoolmix/luniz_i_got_5_on_it.mp3", title = "I Got 5 On It", artist = "Luniz", duration = 200 },
            { file = "oldschoolmix/nas_n_y_state_of_mind.mp3", title = "N.Y. State of Mind", artist = "Nas", duration = 200 },
            { file = "oldschoolmix/plan_b_fanatica_sensual.mp3", title = "Fanatica Sensual", artist = "Plan B", duration = 200 },
            { file = "oldschoolmix/r_k_m_ken_y_down.mp3", title = "Down", artist = "R.K.M & Ken-Y", duration = 200 },
            { file = "oldschoolmix/tego_calderon_punto_y_aparte.mp3", title = "Punto y Aparte", artist = "Tego Calderón", duration = 200 },
            { file = "oldschoolmix/the_notorious_b_i_g_big_poppa_2005_remaster.mp3", title = "Big Poppa - 2005 Remaster", artist = "The Notorious B.I.G.", duration = 200 },
            { file = "oldschoolmix/the_notorious_b_i_g_juicy_2005_remaster.mp3", title = "Juicy - 2005 Remaster", artist = "The Notorious B.I.G.", duration = 200 },
            { file = "oldschoolmix/tito_el_bambino_chequea_como_se_siente.mp3", title = "Chequea Cómo Se Siente", artist = "Tito _El Bambino_", duration = 200 },
            { file = "oldschoolmix/tony_dize_el_doctorado.mp3", title = "El Doctorado", artist = "Tony Dize", duration = 200 },
            { file = "oldschoolmix/tony_dize_solos.mp3", title = "Solos", artist = "Tony Dize", duration = 200 },
            { file = "oldschoolmix/trebol_clan_gata_fiera_feat_joan.mp3", title = "Gata Fiera (feat. Joan)", artist = "Trebol Clan", duration = 200 },
            { file = "oldschoolmix/wisin_yandel_abusadora.mp3", title = "Abusadora", artist = "Wisin & Yandel", duration = 200 },
            { file = "oldschoolmix/wisin_yandel_mayor_que_yo.mp3", title = "Mayor Que Yo", artist = "Wisin & Yandel", duration = 200 },
            { file = "oldschoolmix/wisin_yandel_mirala_bien.mp3", title = "Mírala Bien", artist = "Wisin & Yandel", duration = 200 },
            { file = "oldschoolmix/zion_lennox_doncella.mp3", title = "Doncella", artist = "Zion & Lennox", duration = 200 },
            { file = "oldschoolmix/zion_amor_de_pobre.mp3", title = "Amor De Pobre", artist = "Zion", duration = 200 },
            { file = "oldschoolmix/zion_more.mp3", title = "More", artist = "Zion", duration = 200 },
            { file = "oldschoolmix/nejo_dalmata_pasarela.mp3", title = "Pasarela", artist = "Ñejo & Dalmata", duration = 200 },
        },
    },
    {
        id = 'OB_RADIO_8',
        label = 'Nostalgia Radio',
        logo = 'nostalgia.png',
        songs = {
            { file = "nostalgiamix/50_cent_candy_shop.mp3", title = "Candy Shop", artist = "50 Cent", duration = 200 },
            { file = "nostalgiamix/alesso_heroes_we_could_be.mp3", title = "Heroes (we could be)", artist = "Alesso", duration = 200 },
            { file = "nostalgiamix/arnon_te_molla.mp3", title = "Te Molla", artist = "Arnon", duration = 200 },
            { file = "nostalgiamix/baby_bash_cyclone_feat_t_pain_main.mp3", title = "Cyclone (feat. T-Pain) - Main", artist = "Baby Bash", duration = 200 },
            { file = "nostalgiamix/black_eyed_peas_rock_that_body.mp3", title = "Rock That Body", artist = "Black Eyed Peas", duration = 200 },
            { file = "nostalgiamix/calvin_harris_how_deep_is_your_love.mp3", title = "How Deep Is Your Love", artist = "Calvin Harris", duration = 200 },
            { file = "nostalgiamix/calvin_harris_this_is_what_you_came_for.mp3", title = "This Is What You Came For", artist = "Calvin Harris", duration = 200 },
            { file = "nostalgiamix/chris_brown_run_it_feat_juelz_santana.mp3", title = "Run It! (feat. Juelz Santana)", artist = "Chris Brown", duration = 200 },
            { file = "nostalgiamix/ciara_1_2_step_feat_missy_elliott.mp3", title = "1, 2 Step (feat. Missy Elliott)", artist = "Ciara", duration = 200 },
            { file = "nostalgiamix/david_guetta_love_is_gone_fred_riester_joachim_garraud_radio_edit_remix.mp3", title = "Love Is Gone - Fred Riester & Joachim Garraud Radio Edit Remix", artist = "David Guetta", duration = 200 },
            { file = "nostalgiamix/eiffel_65_blue_da_ba_dee_gabry_ponte_ice_pop_radio.mp3", title = "Blue (Da Ba Dee) - Gabry Ponte Ice Pop Radio", artist = "Eiffel 65", duration = 200 },
            { file = "nostalgiamix/flo_rida_right_round.mp3", title = "Right Round", artist = "Flo Rida", duration = 200 },
            { file = "nostalgiamix/jason_derulo_don_t_wanna_go_home.mp3", title = "Don't Wanna Go Home", artist = "Jason Derulo", duration = 200 },
            { file = "nostalgiamix/justin_bieber_beauty_and_a_beat.mp3", title = "Beauty And A Beat", artist = "Justin Bieber", duration = 200 },
            { file = "nostalgiamix/justin_timberlake_sexyback_feat_timbaland.mp3", title = "SexyBack (feat. Timbaland)", artist = "Justin Timberlake", duration = 200 },
            { file = "nostalgiamix/kesha_die_young.mp3", title = "Die Young", artist = "Kesha", duration = 200 },
            { file = "nostalgiamix/lady_gaga_just_dance.mp3", title = "Just Dance", artist = "Lady Gaga", duration = 200 },
            { file = "nostalgiamix/marshmello_alone.mp3", title = "Alone", artist = "Marshmello", duration = 200 },
            { file = "nostalgiamix/mike_posner_i_took_a_pill_in_ibiza_seeb_remix.mp3", title = "I Took A Pill In Ibiza - Seeb Remix", artist = "Mike Posner", duration = 200 },
            { file = "nostalgiamix/nicki_minaj_super_bass.mp3", title = "Super Bass", artist = "Nicki Minaj", duration = 200 },
            { file = "nostalgiamix/pitbull_don_t_stop_the_party_feat_tjr.mp3", title = "Don't Stop the Party (feat. TJR)", artist = "Pitbull", duration = 200 },
            { file = "nostalgiamix/pitbull_hey_baby_drop_it_to_the_floor_feat_t_pain.mp3", title = "Hey Baby (Drop It to the Floor) (feat. T-Pain)", artist = "Pitbull", duration = 200 },
            { file = "nostalgiamix/pitbull_international_love_feat_chris_brown.mp3", title = "International Love (feat. Chris Brown)", artist = "Pitbull", duration = 200 },
            { file = "nostalgiamix/r_i_o_party_shaker_video_edit.mp3", title = "Party Shaker - Video Edit", artist = "R.I.O.", duration = 200 },
            { file = "nostalgiamix/sean_kingston_take_you_there.mp3", title = "Take You There", artist = "Sean Kingston", duration = 200 },
            { file = "nostalgiamix/sean_paul_when_you_gonna_give_it_up_to_me_radio_version.mp3", title = "(When You Gonna) Give It Up to Me - Radio Version", artist = "Sean Paul", duration = 200 },
            { file = "nostalgiamix/sean_paul_get_busy.mp3", title = "Get Busy", artist = "Sean Paul", duration = 200 },
            { file = "nostalgiamix/sean_paul_she_doesn_t_mind.mp3", title = "She Doesn't Mind", artist = "Sean Paul", duration = 200 },
            { file = "nostalgiamix/shakira_hips_don_t_lie_feat_wyclef_jean.mp3", title = "Hips Don't Lie (feat. Wyclef Jean)", artist = "Shakira", duration = 200 },
            { file = "nostalgiamix/soulja_boy_crank_that_soulja_boy.mp3", title = "Crank That (Soulja Boy)", artist = "Soulja Boy", duration = 200 },
            { file = "nostalgiamix/soulja_boy_kiss_me_thru_the_phone.mp3", title = "Kiss Me Thru The Phone", artist = "Soulja Boy", duration = 200 },
            { file = "nostalgiamix/stromae_alors_on_danse_radio_edit.mp3", title = "Alors on danse - Radio Edit", artist = "Stromae", duration = 200 },
            { file = "nostalgiamix/taio_cruz_hangover.mp3", title = "Hangover", artist = "Taio Cruz", duration = 200 },
            { file = "nostalgiamix/timbaland_give_it_to_me.mp3", title = "Give It To Me", artist = "Timbaland", duration = 200 },
            { file = "nostalgiamix/usher_more_redone_jimmy_joker_remix.mp3", title = "More - RedOne Jimmy Joker Remix", artist = "USHER", duration = 200 },
            { file = "nostalgiamix/usher_yeah_feat_lil_jon_ludacris.mp3", title = "Yeah! (feat. Lil Jon & Ludacris)", artist = "USHER", duration = 200 },
        },
    },
    {
        id = 'OB_RADIO_9',
        label = 'Spanish Radio',
        logo = '7-3radio.png',
        songs = {
            { file = "spanishradio/beatboy_pase_y_toque.mp3", title = "Pase y Toque", artist = "BeatBoy", duration = 200 },
            { file = "spanishradio/gabito_ballesteros_7_dias.mp3", title = "7 DÍAS", artist = "Gabito Ballesteros", duration = 200 },
            { file = "spanishradio/jasiel_nunez_amiri.mp3", title = "AMIRI", artist = "Jasiel Nuñez", duration = 200 },
            { file = "spanishradio/jasiel_nunez_la_lleca.mp3", title = "La Lleca", artist = "Jasiel Nuñez", duration = 200 },
            { file = "spanishradio/junior_h_droga_letal.mp3", title = "DROGA LETAL", artist = "Junior H", duration = 200 },
            { file = "spanishradio/junior_h_el_azul.mp3", title = "El Azul", artist = "Junior H", duration = 200 },
            { file = "spanishradio/junior_h_las_noches.mp3", title = "LAS NOCHES", artist = "Junior H", duration = 200 },
            { file = "spanishradio/junior_h_mi_llamada.mp3", title = "MI$ LLAMADA$", artist = "Junior H", duration = 200 },
            { file = "spanishradio/junior_h_y_lloro.mp3", title = "Y LLORO", artist = "Junior H", duration = 200 },
            { file = "spanishradio/lenin_ramirez_a_que_sabes.mp3", title = "A Que Sabes", artist = "Lenin Ramírez", duration = 200 },
            { file = "spanishradio/lenin_ramirez_todo_lo_fue.mp3", title = "Todo Lo Fue", artist = "Lenin Ramírez", duration = 200 },
            { file = "spanishradio/los_dareyes_de_la_sierra_frecuencia.mp3", title = "Frecuencia", artist = "Los Dareyes De La Sierra", duration = 200 },
            { file = "spanishradio/luis_r_conriquez_la_fiesta.mp3", title = "La Fiesta", artist = "Luis R Conriquez", duration = 200 },
            { file = "spanishradio/neton_vega_morena.mp3", title = "Morena", artist = "Neton Vega", duration = 200 },
            { file = "spanishradio/omar_camacho_2_2.mp3", title = "2+2", artist = "Omar Camacho", duration = 200 },
            { file = "spanishradio/omar_camacho_4x4.mp3", title = "4x4", artist = "Omar Camacho", duration = 200 },
            { file = "spanishradio/oscar_maydon_amigos_no.mp3", title = "Amigos_ No.", artist = "Oscar Maydon", duration = 200 },
            { file = "spanishradio/peso_pluma_belanova.mp3", title = "BELANOVA", artist = "Peso Pluma", duration = 200 },
            { file = "spanishradio/peso_pluma_santal_33.mp3", title = "SANTAL 33", artist = "Peso Pluma", duration = 200 },
            { file = "spanishradio/peso_pluma_chiclona.mp3", title = "chiclona", artist = "Peso Pluma", duration = 200 },
            { file = "spanishradio/peso_pluma_dopamina.mp3", title = "dopamina", artist = "Peso Pluma", duration = 200 },
            { file = "spanishradio/peso_pluma_marianita.mp3", title = "marianita", artist = "Peso Pluma", duration = 200 },
            { file = "spanishradio/peso_pluma_putielegante.mp3", title = "putielegante", artist = "Peso Pluma", duration = 200 },
            { file = "spanishradio/regulo_molina_canasteo.mp3", title = "Canasteo", artist = "Régulo Molina", duration = 200 },
            { file = "spanishradio/tito_double_p_5_7.mp3", title = "5-7", artist = "Tito Double P", duration = 200 },
            { file = "spanishradio/tito_double_p_dos_dias.mp3", title = "DOS DÍAS", artist = "Tito Double P", duration = 200 },
            { file = "spanishradio/tito_double_p_el_lokeron.mp3", title = "EL LOKERON", artist = "Tito Double P", duration = 200 },
            { file = "spanishradio/tito_double_p_escapate.mp3", title = "ESCAPATE", artist = "Tito Double P", duration = 200 },
            { file = "spanishradio/tito_double_p_por_sus_besos.mp3", title = "POR SUS BESOS", artist = "Tito Double P", duration = 200 },
            { file = "spanishradio/tito_double_p_rosones.mp3", title = "ROSONES", artist = "Tito Double P", duration = 200 },
            { file = "spanishradio/victor_mendivil_king_of_watches.mp3", title = "King of Watches", artist = "Victor Mendivil", duration = 200 },
        },
    },
}
